name: chargebee_flutter
description: This is the official Software Development Kit (SDK) for Chargebee Flutter.
version: 0.0.1
homepage: 'https://chargebee.com'
repository: 'https://github.com/chargebee/chargebee-flutter'

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  progress_dialog_null_safe: ^1.0.4

  flutter:
    sdk: flutter
  collection: ^1.15.0
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^4.1.3
  build_runner: ^2.1.0

# The following section is specific to Flutter.
flutter:

  plugin:
    platforms:
      android:
        package: com.chargebee.flutter.sdk
        pluginClass: ChargebeeFlutterSdkPlugin
      ios:
        pluginClass: ChargebeeFlutterSdkPlugin

